// <auto-generated />
using BikeRentalCompany0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRentalCompany0.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220617133752_AddClientsToDatabase")]
    partial class AddClientsToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BikeRentalCompany0.Models.Bike", b =>
                {
                    b.Property<int>("IdRoweru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoweru"), 1L, 1);

                    b.Property<string>("NazwaRoweru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RozmiarKola")
                        .HasColumnType("int");

                    b.HasKey("IdRoweru");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("BikeRentalCompany0.Models.Client", b =>
                {
                    b.Property<int>("IdKlienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKlienta"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NrTelefonu")
                        .HasColumnType("float");

                    b.HasKey("IdKlienta");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
