// <auto-generated />
using System;
using BikeRentalCompany0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRentalCompany0.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BikeRentalCompany0.Models.Bike", b =>
                {
                    b.Property<int>("IdRoweru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoweru"), 1L, 1);

                    b.Property<string>("NazwaRoweru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RozmiarKola")
                        .HasColumnType("int");

                    b.HasKey("IdRoweru");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("BikeRentalCompany0.Models.Client", b =>
                {
                    b.Property<int>("IdKlienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKlienta"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NrTelefonu")
                        .HasColumnType("float");

                    b.HasKey("IdKlienta");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BikeRentalCompany0.Models.Rental", b =>
                {
                    b.Property<int>("IdWynajmu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWynajmu"), 1L, 1);

                    b.Property<DateTime>("DataOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdKlienta")
                        .HasColumnType("int");

                    b.Property<int>("IdPracownika")
                        .HasColumnType("int");

                    b.Property<int>("IdRoweru")
                        .HasColumnType("int");

                    b.Property<int>("IloscDni")
                        .HasColumnType("int");

                    b.HasKey("IdWynajmu");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("BikeRentalCompany0.Models.Worker", b =>
                {
                    b.Property<int>("IdPracownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPracownika"), 1L, 1);

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NrTelefonu")
                        .HasColumnType("float");

                    b.HasKey("IdPracownika");

                    b.ToTable("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
